version: '3.8'

services:
  web:
    build: ./app  # Путь к вашему Flask приложению
    container_name: web
    ports:
      - "5000:5000"  # Проброс порта 5000 на хостовую машину
    networks:
      - monitoring
    labels:
      - "prometheus_job=flask_app"
    volumes:
      - ./app:/app  # Монтируем локальную папку с кодом в контейнер
    environment:
      - FLASK_APP=app.py  # Указание на главный файл приложения
      - FLASK_ENV=development  # Установка режима разработки
      - FLASK_DEBUG=1  # Включает режим отладки
      - DATABASE_URL=${DATABASE_URL}  # Строка подключения к базе данных
  # Сервис для PostgreSQL
  db:
    image: postgres:latest  # Используем официальную PostgreSQL-образ
    container_name: db
    environment:
      - POSTGRES_USER=postgres  # Имя пользователя
      - POSTGRES_PASSWORD=${DB_PASSWORD}  # Пароль пользователя
      - POSTGRES_DB=musicdb  # Название базы данных
    volumes:
      - ./db_data:/var/lib/postgresql/data  # Храним данные базы данных в volume
    networks:
      - monitoring

  postgresexporter:
    image: prometheuscommunity/postgres-exporter:latest
    environment:
      DATA_SOURCE_NAME: ${DATABASE_URL}
    ports:
      - "9187:9187"
    volumes:
      - ./pg_exporter/queries.yml:/etc/queries.yml
    command:
      - '--web.listen-address=:9187'
      - '--web.telemetry-path=/metrics'
      - '--collector.database_wraparound'
      - '--collector.long_running_transactions'
      - '--collector.postmaster'
      - '--collector.process_idle'
      - '--collector.stat_activity_autovacuum'
      - '--collector.stat_statements'
      - '--collector.stat_wal_receiver'
      - '--collector.statio_user_indexes'
      - '--extend.query-path=/etc/queries.yml'
    depends_on:
      - db

  # Сервис для pgAdmin (для удобного доступа к PostgreSQL через браузер)
  pgadmin:
    image: dpage/pgadmin4:latest  # Официальный образ pgAdmin
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com  # Адрес электронной почты для входа
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD_PGA}  # Пароль для входа
      - PGADMIN_LISTEN_PORT=8081
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "8081:8081"  # Доступ через localhost:80
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prom-data:/prometheus
      - prom-configs:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/datasources/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_DASHBOARDS_JSON_ENABLED=true  # Включаем JSON дашборды
      - GF_DASHBOARDS_JSON_PATH=/etc/grafana/dashboards  # Путь к папке с дашбордами
    depends_on:
      - prometheus
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart:
      always
    networks:
      - monitoring

  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - monitoring
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude'
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - "monitoring"
    depends_on:
      - prometheus
      - grafana
      - web
      - cadvisor
      - node_exporter

networks:
  monitoring:
    driver: bridge
volumes:
  grafana_data:
  prom-data:
  prom-configs:
