# version: '3.8'

services:
  db:
    image: postgres:latest  # Используем официальную PostgreSQL-образ
    container_name: db
    environment:
      - POSTGRES_USER=postgres  # Имя пользователя
      - POSTGRES_PASSWORD=${DB_PASSWORD}  # Пароль пользователя
      - POSTGRES_DB=musicdb  # Название базы данных
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - ./db_data:/var/lib/postgresql/data  # Храним данные базы данных в volume
    networks:
      - monitoring

  web:
    build: ./app  # Путь к вашему Flask приложению
    container_name: web
    ports:
      - "5000:5000"  # Проброс порта 5000 на хостовую машину
    networks:
      - monitoring
    labels:
      - "prometheus_job=flask_app"
      - "traefik.enable=true"                                # Включить для Traefik
      - "traefik.http.routers.web.rule=PathPrefix(`/musicservice`)"      # Доступ через корневой маршрут
      - "traefik.http.services.web.loadbalancer.server.port=5000"
    volumes:
      - ./app:/app  # Монтируем локальную папку с кодом в контейнер
      - ./static:/app/static    # Монтирование статических файлов
      - ./templates:/app/templates  # Монтирование шаблонов
    environment:
      - FLASK_APP=app.py  # Указание на главный файл приложения
      # - FLASK_ENV=development  # Установка режима разработки
      - FLASK_DEBUG=1  # Включает режим отладки
      - DATABASE_URL=${DATABASE_URL}  # Строка подключения к базе данных
    depends_on:
      db:
        condition: service_healthy
  
  postgresexporter:
    image: prometheuscommunity/postgres-exporter:latest
    environment:
      DATA_SOURCE_NAME: ${DATABASE_URL}
    ports:
      - "9187:9187"
    networks:
      - monitoring
    volumes:
      - ./pg_exporter/queries.yml:/etc/queries.yml
    command:
      - '--web.listen-address=:9187'
      - '--web.telemetry-path=/metrics'
      - '--collector.database_wraparound'
      - '--collector.long_running_transactions'
      - '--collector.postmaster'
      - '--collector.process_idle'
      - '--collector.stat_activity_autovacuum'
      - '--collector.stat_statements'
      - '--collector.stat_wal_receiver'
      - '--collector.statio_user_indexes'
      - '--extend.query-path=/etc/queries.yml'
    depends_on:
      - db

  # Сервис для pgAdmin (для удобного доступа к PostgreSQL через браузер)
  pgadmin:
    image: dpage/pgadmin4:latest  # Официальный образ pgAdmin
    container_name: pgadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=PathPrefix(`/pgadmin`)"
      - "traefik.http.middlewares.pgadmin-strip-prefix.stripprefix.prefixes=/pgadmin"
      - "traefik.http.routers.pgadmin.middlewares=pgadmin-strip-prefix"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=8081"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com  # Адрес электронной почты для входа
      - PGADMIN_DEFAULT_PASSWORD=admin  # Пароль для входа
      - PGADMIN_LISTEN_PORT=8081
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "8081:8081"  # Доступ через localhost:80
    networks:
      - monitoring
    depends_on:
      - db

  prometheus:
    image: prom/prometheus:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=PathPrefix(`/prometheus`)"
      - "traefik.http.middlewares.prometheus-strip-prefix.stripprefix.prefixes=/prometheus"
      - "traefik.http.routers.prometheus.middlewares=prometheus-strip-prefix"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prom-data:/prometheus
      - prom-configs:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/datasources/
    labels:
      - "traefik.enable=true"                                    # Включить для Traefik
      - "traefik.http.routers.grafana.rule=PathPrefix(`/grafana`)" # Доступ по lotolis/grafana
      - "traefik.http.middlewares.grafana-strip-prefix.stripprefix.prefixes=/grafana"
      - "traefik.http.routers.grafana.middlewares=grafana-strip-prefix"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_DASHBOARDS_JSON_ENABLED=true  # Включаем JSON дашборды
      - GF_DASHBOARDS_JSON_PATH=/etc/grafana/dashboards  # Путь к папке с дашбордами
      - GF_SERVER_ROOT_URL=http://lotolis/grafana/

    depends_on:
      - prometheus
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cadvisor.rule=PathPrefix(`/cadvisor`)"
      - "traefik.http.middlewares.cadvisor-strip-prefix.stripprefix.prefixes=/cadvisor"
      - "traefik.http.routers.cadvisor.middlewares=cadvisor-strip-prefix"
      - "traefik.http.services.cadvisor.loadbalancer.server.port=8080"
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart:
      always
    networks:
      - monitoring

  node_exporter:
    image: prom/node-exporter:latest
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.node_exporter.rule=PathPrefix(`/node_exporter`)"
      - "traefik.http.middlewares.node_exporter-stripprefix.stripprefix.prefixes=/node_exporter"
      - "traefik.http.middlewares.node_exporter-replacepath.replacepath.path=/{path}"
      - "traefik.http.routers.node_exporter.middlewares=node_exporter-stripprefix,node_exporter-replacepath"
      - "traefik.http.services.node_exporter.loadbalancer.server.port=9100"
    ports:
      - "9100:9100"
    networks:
      - monitoring
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude'
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    



  # Logstash
  logstash:
    image: logstash:8.16.2
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf  # Конфиг для pipeline
      # - ./logstash/config/:/usr/share/logstash/config/ 
    ports:
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - monitoring
    environment:
      - LOGSTASH_OUTPUT_ELASTICSEARCH_URL=http://elasticsearch:9200  # Адрес Elasticsearch для отправки данных

  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_LOCAL_VERSION}
    container_name: ${ES_LOCAL_CONTAINER_NAME}
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    networks:
      - monitoring
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ES_LOCAL_PASSWORD}
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      - xpack.ml.use_auto_machine_memory_percent=true
      - ES_JAVA_OPTS=-Xms${ES_LOCAL_HEAP_INIT} -Xmx${ES_LOCAL_HEAP_MAX}
      - cluster.routing.allocation.disk.watermark.low=${ES_LOCAL_DISK_SPACE_REQUIRED}
      - cluster.routing.allocation.disk.watermark.high=${ES_LOCAL_DISK_SPACE_REQUIRED}
      - cluster.routing.allocation.disk.watermark.flood_stage=${ES_LOCAL_DISK_SPACE_REQUIRED}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elasticsearch.rule=PathPrefix(`/elasticsearch`)"
      - "traefik.http.middlewares.elasticsearch-strip-prefix.stripprefix.prefixes=/elasticsearch"
      - "traefik.http.routers.elasticsearch.middlewares=elasticsearch-strip-prefix"
      - "traefik.http.services.elasticsearch.loadbalancer.server.port=9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --output /dev/null --silent --head --fail -u elastic:${ES_LOCAL_PASSWORD} http://elasticsearch:9200",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  # kibana_settings:
  #   depends_on:
  #     elasticsearch:
  #       condition: service_healthy
  #   image: docker.elastic.co/elasticsearch/elasticsearch:${ES_LOCAL_VERSION}
  #   container_name: kibana_settings
  #   restart: 'no'
  #   command: >
  #     bash -c '
  #       echo "Setup the kibana_system password";
  #       start_time=$(date +%s);
  #       timeout=60;
  #       until curl -s -u "elastic:${ES_LOCAL_PASSWORD}" -X POST http://elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"'${KIBANA_LOCAL_PASSWORD}'\"}" -H "Content-Type: application/json" | grep -q "^{}"; do if [ $(($(date +%s) - $$start_time)) -ge $$timeout ]; then echo "Error: Elasticsearch timeout"; exit 1; fi; sleep 2; done;
  #     '

  kibana:
    # depends_on:
    #   kibana_settings:
    #     condition: service_completed_successfully
    image: docker.elastic.co/kibana/kibana:${ES_LOCAL_VERSION}
    container_name: ${KIBANA_LOCAL_CONTAINER_NAME}
    volumes:
      - ./kibana:/usr/share/kibana/data
    ports:
      - "5601:5601"
    networks:
      - monitoring
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_LOCAL_PASSWORD}
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${KIBANA_ENCRYPTION_KEY}
      - ELASTICSEARCH_PUBLICBASEURL=http://localhost:${ES_LOCAL_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kibana.rule=PathPrefix(`/kibana`)"
      - "traefik.http.middlewares.kibana-stripprefix.stripprefix.prefixes=/kibana"
      - "traefik.http.routers.kibana.middlewares=kibana-stripprefix"
      - "traefik.http.services.kibana.loadbalancer.server.port=5601"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://kibana:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 20

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.16.2
    container_name: filebeat
    command: --strict.perms=false -e
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml  # Конфигурация Filebeat
      - ./app/app/logs:/var/log/app_logs # Монтируем логи с хоста (или из других контейнеров)
    networks:
      - monitoring
    depends_on:
      - logstash  # Filebeat должен подключаться к Logstash
    environment:
      - LOGSTASH_HOST=logstash  # Имя сервиса Logstash
      - LOGSTASH_PORT=5044      # Порт, на котором Logstash принимает данные

  # traefik:
  #   image: traefik:v2.10
  #   container_name: traefik
  #   ports:
  #     - "80:80"        # HTTP
  #     - "443:443"      # HTTPS (если нужно)
  #     - "8085:8080"    # Панель управления Traefik
  #   command:
  #     - "--api.insecure=true"                    # Включаем панель управления (доступно на http://lotolis:8080)
  #     - "--providers.docker=true"                # Автоматическое обнаружение сервисов в Docker
  #     - "--entrypoints.web.address=:80"          # Основной HTTP-вход
  #     - "--entrypoints.websecure.address=:443"   # HTTPS (при необходимости)
  #     - "--log.level=INFO" 
  #     - "--configFile=/etc/traefik/traefik.yml"                       # Уровень логирования
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock # Для взаимодействия с Docker
  #     - ./traefik/traefik.yml:/etc/traefik/traefik.yml
  #   networks:
  #     - monitoring
  #   depends_on:
  #     - elasticsearch
  #     - cadvisor
  #     - prometheus
  #     - node_exporter
  #     - web
  #     - grafana
  #     - kibana
  #     - pgadmin
networks:
  monitoring:
    driver: bridge
volumes:
  grafana_data:
  prom-data:
  prom-configs:
  es-data:
  kibana:
  logstash:
  filebeat:

