api:
  insecure: true  # Включаем insecure API для доступа к панели управления (не рекомендуется для продакшн-среды)

providers:
  docker:
    exposedByDefault: false  # По умолчанию не показывать все сервисы в Traefik, только те, которые явно помечены метками

http:
  routers:
    app:
      rule: "PathPrefix(`/musicservice`)"  # Доступ по lotolis/musicservice
      service: app
      entryPoints:
        - web


    node_exporter:
      rule: "PathPrefix(`/node_exporter`)"
      service: node_exporter
      entryPoints:
        - web
      middlewares:
        - node_exporter-strip-prefix

    grafana:
      rule: "PathPrefix(`/grafana`)"
      service: grafana
      entryPoints:
        - web
      middlewares:
        - grafana-strip-prefix

    pgadmin:
      rule: "PathPrefix(`/pgadmin`)"
      service: pgadmin
      entryPoints:
        - web
      middlewares:
        - pgadmin-strip-prefix

    cadvisor:
      rule: "PathPrefix(`/cadvisor`)"
      service: cadvisor
      entryPoints:
        - web
      middlewares:
        - cadvisor-strip-prefix

    prometheus:
      rule: "PathPrefix(`/prometheus`)"
      service: prometheus
      entryPoints:
        - web
      middlewares:
        - prometheus-strip-prefix

    traefik:
      rule: "PathPrefix(`/traefik`)"
      service: traefik
      entryPoints:
        - web
      middlewares:
        - traefik-strip-prefix

    kibana:
      rule: "PathPrefix(`/kibana`)"
      service: kibana
      entryPoints:
        - web
      middlewares:
        - kibana-strip-prefix

    elasticsearch:
      rule: "PathPrefix(`/elasticsearch`)"
      service: elasticsearch
      entryPoints:
        - web
      middlewares:
        - elasticsearch-strip-prefix

  middlewares:
    app-strip-prefix:
      stripPrefix:
        prefixes:
          - "/musicservice"

    node_exporter-strip-prefix:
      stripPrefix:
        prefixes:
          - "/node_exporter"

    grafana-strip-prefix:
      stripPrefix:
        prefixes:
          - "/grafana"

    prometheus-strip-prefix:
      stripPrefix:
        prefixes:
          - "/prometheus"

    cadvisor-strip-prefix:
      stripPrefix:
        prefixes:
          - "/cadvisor"

    pgadmin-strip-prefix:
      stripPrefix:
        prefixes:
          - "/pgadmin"

    traefik-strip-prefix:
      stripPrefix:
        prefixes:
          - "/traefik"

    kibana-strip-prefix:
      stripPrefix:
        prefixes:
          - "/kibana"

    elasticsearch-strip-prefix:
      stripPrefix:
        prefixes:
          - "/elasticsearch"

  services:
    app:
      loadBalancer:
        servers:
          - url: "http://app:5000"

    node_exporter:
      loadBalancer:
        servers:
          - url: "http://node_exporter:9100"

    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"

    prometheus:
      loadBalancer:
        servers:
          - url: "http://prometheus:9090"

    cadvisor:
      loadBalancer:
        servers:
          - url: "http://cadvisor:8080"

    pgadmin:
      loadBalancer:
        servers:
          - url: "http://pgadmin:8081"

    traefik:
      loadBalancer:
        servers:
          - url: "http://traefik:8080"

    kibana:
      loadBalancer:
        servers:
          - url: "http://kibana:5601"

    elasticsearch:
      loadBalancer:
        servers:
          - url: "http://elasticsearch:9200"

entryPoints:
  web:
    address: ":80"  # Основной HTTP вход

# Логи Traefik
log:
  level: "INFO"
  filePath: "/var/log/traefik.log"

# Включение панели управления Traefik
dashboard:
  enabled: true
  entryPoint: web