# Основная конфигурация для Traefik
api:
  insecure: true  # Включаем insecure API для доступа к панели управления (не рекомендуется для продакшн-среды)

providers:
  docker:
    exposedByDefault: false  # По умолчанию не показывать все сервисы в Traefik, только те, которые явно помечены метками

http:
  routers:
    # Пример маршрутизатора для веб-приложения
    web:
      rule: "PathPrefix(`/`)"
      service: web
      entryPoints:
        - web
    node_exporter:
      rule: "PathPrefix(`/node_exporter`)"
      service: node_exporter
      entryPoints:
        - web
      middlewares:
        - node_exporter-stripprefix  # Применение middleware для node_exporter
    grafana:
      rule: "PathPrefix(`/grafana`)"
      service: grafana
      entryPoints:
        - web
      middlewares:
        - grafana-stripprefix  # Применение middleware для grafana
    pgadmin:
      rule: "PathPrefix(`/pgadmin`)"
      service: pgadmin
      entryPoints:
        - web
      middlewares:
        - pgadmin-stripprefix
    cadvisor:
      rule: "PathPrefix(`/cadvisor`)"
      service: cadvisor
      entryPoints:
        - web
      middlewares:
        - cadvisor-stripprefix
    prometheus:
      rule: "PathPrefix(`/prometheus`)"
      service: prometheus
      entryPoints:
        - web
      middlewares:
        - prometheus-stripprefix
    traefik:
      rule: "PathPrefix(`/traefik`)"
      service: traefik
      entryPoints:
        - web
      middlewares:
        - traefik-stripprefix

  middlewares:
    # Middleware для удаления префикса из пути
    node_exporter-stripprefix:
      stripPrefix:
        prefixes:
          - "/node_exporter"  # Удаляем префикс /node_exporter

    # Middleware для удаления префикса из пути
    grafana-stripprefix:
      stripPrefix:
        prefixes:
          - "/grafana"  # Удаляем префикс /grafana
    
    prometheus-stripprefix:
      stripPrefix:
        prefixes:
          - "/prometheus"

    cadvisor-stripprefix:
      stripPrefix:
        prefixes:
          - "/cadvisor"
    
    pgadmin-stripprefix:
      stripPrefix:
        prefixes:
          - "/pgadmin" 
    traefik-stripprefix:
      stripPrefix:
        prefixes:
          - "/traefik" 

  services:
    # Пример сервисов
    web:
      loadBalancer:
        servers:
          - url: "http://lotolis:5000"  # Указание сервера для приложения Flask
    node_exporter:
      loadBalancer:
        servers:
          - url: "http://lotolis:9100"  # Указание сервера для node_exporter
    grafana:
      loadBalancer:
        servers:
          - url: "http://lotolis:3000"  # Указание сервера для grafana

    prometheus:
      loadBalancer:
        servers:
          - url: "http://lotolis:9090"
    
    cadvisor:
      loadBalancer:
        servers:
          - url: "http://lotolis:8080"

    pgadmin:
      loadBalancer:
        servers:
          - url: "http://lotolis:8081"
    
    traefik:
      loadBalancer:
        servers:
          - url: "http://lotolis:8085"

entryPoints:
  web:
    address: ":80"  # Основной HTTP вход

# Логи Traefik
log:
  level: "INFO"  # Уровень логирования
  filePath: "/var/log/traefik.log"  # Путь для записи логов

# Включение панели управления Traefik
dashboard:
  enabled: true  # Включение панели управления
  entryPoint: web
